config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts

  root "posts#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3}
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end


private
    def post_params
      params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© peterkona</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <link href="http://fonts.googleapis.com/css?family=Oleo+Script" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
      <!--<ul class="button-group">-->
        <!--<li><a href="#" class="button">Link 1</a></li>-->
        <!--<li><a href="#" class="button">Link 2</a></li>-->
        <!--<li><a href="#" class="button">Link 3</a></li>-->
        <!--<li><a href="#" class="button">Link 4</a></li>-->
      <!--</ul>-->
    </div>
    <div class="header">
    <div id="logo">
      <%= link_to root_path do %>
          <%= image_tag "logo.svg" %>
          <!--<p>ikona blog</p>-->
      <% end %>
    </div>
    <h1 class="ggn">Dev Blog </h1>
    <h4 class="title4">Code never lies, comments sometimes do.
      </h4>
    <h6 class="titlee">— Ron Jeffries</h6>
</br>
    </div>
  </div>
</div>


<div class="row">


  <div class="large-9 columns" role="content">
    <hr/>
    <div class="buttons">

      <%= link_to "All Post", root_path, :class => :button %>
  <%= link_to "New Post", new_post_path, :class => :button %>

      <% if user_signed_in? %>
          <li><%= link_to 'Edit account', edit_user_registration_path, :class => :button %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', :class => :button %></li>
      <% end %>

      <button class="button"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    Log Out</button>
    </div>
    <hr/>

    <article>

      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert") %>
      <% end %>
      <hr/>
      <%= yield %>
      <hr/>
    </article>

  </div>

  <aside class="large-3 columns">

    <h5>Categories</h5>
    <ul class="side-nav">
      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %></li>
        <li>About</li>
      </ul>

      <ul>
        <li class="category">Social</li>
        <li><a href="https://twitter.com/ikona23">Twitter</a></li>
        <li><a href="http://instagram.com/ikona23">Instagram</a></li>
        <li><a href="https://github.com/ikona23">Github</a></li>
        <li><a href="mailto:ikona23@gmail.com">Email</a></li>
      </ul>

      <a href class="sign_in">Admin Login</a>

    </ul>

    <div class="panel">
      <h5>Dev blog</h5>
      <p> This is the place for question and answers, about web_dev
      </p>
      <a href="http://peterkona.herokuapp.com">Please check my presonal website →</a>
    </div>
  </aside>
</div>

<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Peter Kona</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <div class="buttons">

            <button class="button"><%= link_to "All Post", root_path %></button>
            <button class="button"><%= link_to "New Post", new_post_path %></button>
            <button class="button">Log In</button>
            <button class="button">Log Out</button>
          </div>
        </ul>
      </div>
    </div>
  </div>
</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
    <%= f.label :Problem %><br>
    <%= f.text_field :title %>
    </p>
    <p>
    <%= f.label :Solution %><br>
    <%= f.text_area :body  %>
    </p>
    <p>
    <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post_wrapper">
      <h2 class="title"><%= link_to post.title, post %></h2>
      <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_field :body %><br>
    <br>
    <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
     <% if user_signed_in? %>
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
  </p>
  <p class="body">
    <%= @post.body %>
  </p>
</div>